version: "3.5"

services:
  mynginx:
    build:
      context: ./nginx
    container_name: mynginx
    hostname: 0.0.0.0
    ports:
      - "80:80"
      - "20022:20022"
    volumes:
      - ../app/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx/
      - ./sshd_config:/etc/ssh/sshd_config
    networks:
      - zxc

networks:
  zxc: